name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
    # You may pin to the exact commit or the version.
    # uses: ATiltedTree/setup-rust@749afc283f2b846eb90a670e757de9da4da091f7
      uses: ATiltedTree/setup-rust@v1.0.5
      with:
        # The version to install
        rust-version: 1.63.0
    - name: Install dependencies
      run: make

    - name: Run check
      run: make test
